[main]
include=/usr/share/foot/themes/gruvbox-dark

# globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode
app-id=foot 
title=foot
locked-title=no

font=UbuntuMono Nerd Font:size=12
pad=5x2
letter-spacing=0px
